### ISSUE TITLE
POSTing Java Object as JSON

### ISSUE THREAD

**Issue by michaelsalvia** [jwagenleitner/groovy-wslite#106]
I am currently switching from HttpBuilder to use wslite and I have ran into a road block of sorts.

I am having trouble using my Java Objects (payloads) as my POST body.

``` groovy
when: "a POST is made to 'releases' endpoint"
ReleasePayload releasePayload = new ReleasePayload();
def response = client.post(path: "/releases") {
      json releasePayload 
}
```

Previously with HTTPBuilder I was able to simply provide the object to the client and it would transform it as needed.

``` groovy
when: "a POST is made to 'releases' endpoint"
ReleasePayload releasePayload = new ReleasePayload();
def response = client.post(path: "/releases", contentType: "application/json", body: releasePayload)
```

My ReleasePayload Object is a simple Object containing main Strings, is there a transformation step I need to perform?

Ideally, I would like to continue to use Java's Object for payload-release objects due to the simplicity of being able to modified them slightly for negative testing.

Receiving the following message from the code I provided in 1st snippet.

```groovy.lang.MissingMethodException: No signature of method: wslite.rest.ContentBuilder.json() is applicable for argument types: (java.lang.Class) values: [class java.lang.Object]
Possible solutions: json(), json(java.util.List), json(java.util.Map), use([Ljava.lang.Object;), use(java.lang.Class, groovy.lang.Closure), is(java.lang.Object)```

**Comment by michaelsalvia** [comment]
I have been reviewing the contents of:

https://github.com/jwagenleitner/groovy-wslite/blob/master/src/main/groovy/wslite/rest/ContentBuilder.groovy

From what I am seeing the only things that json(*) would accept would be a Map or List for transformations to JSON.

**Comment by batemansw** [comment]
You can try
client.post(path: '/releases', contentType: 'application/json') {
     json groovy.json.JsonOutput.toJson( new ReleasePayload() )
}

**Comment by jwagenleitner** [comment]
Wslite currently doesn't automatically deserialize objects.  As suggested you can use JsonOutput.toJson to create the actual json text and use the `text` method:

```groovy
client.post(path: '/releases', contentType: 'application/json') {
    text(groovy.json.JsonOutput.toJson( new ReleasePayload() ))
}
```

**Comment by michaelsalvia** [comment]
Thank you this should work! :+1:
