### ISSUE TITLE
Cannot choose the protocol (SSL or TLS).

### ISSUE THREAD

**Issue by fchristol** [jwagenleitner/groovy-wslite#119]
Hello, I'm using WSLITE and it's pretty cool.

But SSLV3 is about to be disabled in most of the HTTPS servers for security reasons. Only TLS protocol will remain. The problem is that WSLITE does not allow protocol selection. Indeed, protocol is forced to 'SSL' in the HTTPConnectionFactory class.

It would be cool to allow protocol selection with an additional configuration parameter as follows : 

		protocol = 'SSL'  // The protocol name passed to SSLContext.getInstance()
		sslTrustAllCerts = false
		sslTrustStoreFile = 'xxx'
		sslTrustStorePassword = 'xxx'
		proxy = myHttpProxy
		connectTimeout = 5000
		readTimeout = 10000

Thanks.

**Comment by rundis** [comment]
I guess a quick fix could be to change the default to 'SSL_TLS'. The making it configurable. This will hit us on several of our app, but I guess we can workaround it with some metaprogramming hacks ?

**Comment by rundis** [comment]
If you don't have limited time I'm sure I could try to submit a PR if you are interested in that.

**Comment by jwagenleitner** [comment]
PR for this would be welcomed.

**Comment by fchristol** [comment]
Hi guys,

It's very kind of you to consider my demand. Anyway I made some tests, and
it appears that Java is able to automatically chose between SSL or TLS
according to what remote server requires. Unless you set an env variable (I
don't remember its name) to force the protocol, everything works well as
is.  So, as far as I'm concerned, no code change is needed.

Thanks a lot.
Le 14 avr. 2016 9:47 AM, "Magnus Rundberget" <notifications@github.com> a
écrit :

I guess a quick fix could be to change the default to 'SSL_TLS'. The making
it configurable. This will hit us on several of our app, but I guess we can
workaround it with some metaprogramming hacks ?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jwagenleitner/groovy-wslite/issues/119#issuecomment-209811580>

**Comment by jwagenleitner** [comment]
Thanks for the feedback, I'll go ahead and close this.
