### ISSUE TITLE
Q: Howto upload files to Nexus using WSLite?

### ISSUE THREAD

**Issue by dhs-rec** [jwagenleitner/groovy-wslite#150]
Unfortunately, all examples in the [Nexus 3 documentation](https://help.sonatype.com/repomanager3/rest-and-integration-api/components-api) are using `curl`, but I'd need to write a Groovy program to mass-upload files to Nexus using its REST API (for an Artifactory to Nexus migration). However, I have no idea about how to translate those `curl` commands to Groovy code. Would be glad if someone could point me in the right direction for [this example](https://help.sonatype.com/repomanager3/rest-and-integration-api/components-api#ComponentsAPI-UploadaPOMandassociatedJARFile).

Thanks a lot!

**Comment by Hubbitus** [comment]
I think you need multipart example from the https://github.com/jwagenleitner/groovy-wslite#sending-content

**Comment by dhs-rec** [comment]
Thanks a lot. I've meanwhile found a method by reading the code of the Jenkins Nexus plugin, which uses an undocumented Nexus platform api jar (com.sonatype.nexus:nexus-platform-api) to do Maven 2 uploads.
