### ISSUE TITLE
Add cookie support for Session-based WS

### ISSUE THREAD

**Issue by grooveek** [jwagenleitner/groovy-wslite#26]
WS which are session-based (multi-operation with connect first and without token) are not handled by this library

If the HTTP library handled cookies, that would enable users using this kind of WS

EX : I have to connect to a SOAP webservice which has a Connect method which is to call first
subsequent calls to other operations trigger SOAPFault : "you are not connected"

**Comment by mjstealth** [comment]
I am also dealing with this issue as well.
