### ISSUE TITLE
Trouble with Keystores

### ISSUE THREAD

**Issue by azesch** [jwagenleitner/groovy-wslite#34]
Hi!

I love wslite. I am not trying to connect to a keystone that requires client authentication and when I specify sslKeystoreFile etc and whether or not I send it in on the send() call with a map or use System.setProperty(), I keep getting the following error:

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I am using Grails 1.3.7 and running on amazon elastic beanstalk but this error is actually happening on my development machine.

Would you have any ideas about how to fix/where to put the .jks files (preferably somewhere in the war file so I can upload into the EBS and not have to rebuild my site's environment using a custom image.)

THANKS!

**Comment by facudm** [comment]
Hi, azesch!
Can you explain me how did you do to make it work wslite with SSL client certificate.
I need to know how to configurate a ketystore as pkcs12 type and then set javax.net.ssl.trustStore, and javax.net.ssl.trustStorePassword properties.
If you send me an example will be marvelous.

Thanks in advance.
Facundo
