### ISSUE TITLE
Plugin not reading javax.net.ssl.trustStore & javax.net.ssl.trustStorePassword automatically

### ISSUE THREAD

**Issue by rajveera** [jwagenleitner/groovy-wslite#67]
I do the Soap call in this order

trustStoreFilePath = System.getProperty("javax.net.ssl.trustStore")
trustStorePassword = System.getProperty("javax.net.ssl.trustStorePassword")

log.debug "trustStoreFilePath: ${trustStoreFilePath}, trustStorePassword: ${trustStorePassword}"

def client = new SOAPClient(wsdlURI)

// The calls are not working without the below two settings.
client.httpClient.sslTrustStoreFile = 	trustStoreFilePath
client.httpClient.sslTrustStorePassword = trustStorePassword

def soapResponse = client.send( [SOAPAction: ''], soapRequest)

I looked at the HTTPClient code and I don't see anywhere the code reading the above System properties.  

The plugin notes says

In addition to setting a global trust store and trust store password using the javax.net.ssl.trustStore and javax.net.ssl.trustStorePassword System properties, you can set a custom trust store on a client.

Am I missing something? Will the code automatically pick the system property settings javax.net.ssl.trustStore & javax.net.ssl.trustStorePassword 
OR should I explicitly set client.httpClient.sslTrustStoreFile & client.httpClient.sslTrustStorePassword ?  

Thanks.

**Comment by jwagenleitner** [comment]
This should be picked up the JDK automatically, note that on Windows there's a requirement for the trustStore file path to have forward slashes `/` instead of backslashes `\`.
