### ISSUE TITLE
DOCTYPE is disallowed

### ISSUE THREAD

**Issue by sw360cab** [jwagenleitner/groovy-wslite#78]
Using version 1.1.0.
I have a valid SOAP message:
1- built in my code creating new SOAPMessageBuilder().build() {}
2- successfully validated and tested here http://wsdlbrowser.com/
3- calling client.send I have the exception
[Fatal Error] :1:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

Reading changelog I was wondering it may have something to do, but didn't changed.

May this have something to do with http://stackoverflow.com/questions/10837706/solve-security-issue-parsing-xml-using-sax-parser

**Comment by facundofarias** [comment]
We were having this issue, but after some investigation we've detected it was due a bad soap response, I mean wslite wasn't receiving a proper SOAP Message.
