### ISSUE TITLE
Method to set the headers for all request

### ISSUE THREAD

**Issue by lmivan** [jwagenleitner/groovy-wslite#79]
I was wondering if it's possible to add a new method to set the headers for all requests. Now, for every request I have to do something like:

```groovy

// Pass the headers with the authentication token
Response response = client.get(path: URLS.projects, headers: headers)

...

// Pass again the same headers
Response response = client.post(path: URLS.projects, headers: headers) {
    json name: project.name,
               description: project.description
}
```

I would be great to have a method to set the headers or to add a new header for all request. With that method I could do:

```groovy
RESTClient client = new RESTClient(serverUrl)
client.setHeaders([Authorization: 'my-auth-token'])
```

What do you think?

**Comment by jwagenleitner** [comment]
I think headers provided in the method parameters should override any default headers.

**Comment by lospejos** [comment]
As per 6 Sept 2016 (Groovy 2.4.7), client.httpClient generates an error (unkown property). I've used restClient.defaultRequestHeaders['headername'] = 'headervalue' instead
