### ISSUE TITLE
Multipart request is not sent correctly

### ISSUE THREAD

**Issue by lmivan** [jwagenleitner/groovy-wslite#83]
In the attached file you can see the differences uploading a file with the browser (top image) and wslite (bottom image). The upload with the browser works ok but the upload with wslite is not working.

* Top image (browser):
 - The file is sent with the correct mime type (image/png)
 - In the multipart request two params are sent `name` and `filename`
 - The bytes are sent with the content-type image/png

* Bottom image (wslite):
 - No mime type
 - Only one param with the name of the parameter but not the name of the file
 - Raw bytes without content-type

![multipart](https://cloud.githubusercontent.com/assets/559192/4089182/2c91c75c-2f68-11e4-9a7c-b91338a66cd9.png)

**Comment by PascalSchumacher** [comment]
@lmivan Can this issue be closed?

**Comment by lmivan** [comment]
I'm sorry but we changed the way we sent the images to the server an I cann't test it anymore.

**Comment by jwagenleitner** [comment]
fixed in v1.1.2 and 2.0-SNAPSHOT
