### ISSUE TITLE
Null responses should be null object instead of "null" (string)

### ISSUE THREAD

**Issue by lmivan** [jwagenleitner/groovy-wslite#85]
Using the RESTClient, with a server response like this:

```
{
    "name": null
}
```

The `name` attribute contains a "null" String instead of a null object.

**Comment by jwagenleitner** [comment]
I'll have to see how Groovy handles this in it's JSON parser.  As a workaround for other that may have this issue the following should work:

```groovy
Integer value = json.value ?: null // or 0
```
