### ISSUE TITLE
HTTPClient connections not being closed

### ISSUE THREAD

**Issue by danboliu** [jwagenleitner/groovy-wslite#86]
By using wslite as REST webservice clients, it appears the code is not closing the underlying socket when the service call fails which is leading to an Out of Memory Error on the application server.

**Comment by jwagenleitner** [comment]
I can't replicate this.

As for timeouts, since read and connect timeouts can easily be set per request or on an instance of an httpclient I think it's best to leave the default URLConnection behavior in place.
