### ISSUE TITLE
how to use nil?

### ISSUE THREAD

**Issue by SimonHobbsNektan** [jwagenleitner/groovy-wslite#92]
We are using the grails wslite 0.7.2.0 plugin (sorry, don't know which version of wslite this uses under the hood, probably the old one).

The API we have to call requires that we send nil, e.g:

    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
          xmlns:ns="bla" xmlns:i="w3.org/2001/XMLSchema-instance">
       :
     <ns:IdentityToken i:nil="true"></ns:IdentityToken>

Is this in any way possible using wsilte?

E.g. how would we send a nil "fromCurrency" in the below sample?

```xml
  def client = new SOAPClient('http://www.webservicex.net/CurrencyConvertor.asmx')
    def response = client.send(SOAPAction:'http://www.webserviceX.NET/ConversionRate') {
        body {
            ConversionRate('xmlns':'http://www.webserviceX.NET/') {
                FromCurrency('GBP')
                ToCurrency('EUR')
            }
        }
    }

**Comment by jwagenleitner** [comment]
Something like this should work...

```groovy
fromCurrency('i:nil': true)
```
