### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ppazos** [jwagenleitner/groovy-wslite#94]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Documents and Settings\pab\My Documents\Downloads\groovy-wslite-master\build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'groovy-wslite-master'.
> Could not find property 'githubUsername' on task ':integrationTest'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 14.708 secs

**Comment by jwagenleitner** [comment]
If you copy `gradle.properties.sample` to `gradle.properties` in the root of the project folder that error should go away.
