### ISSUE TITLE
How to set content-length?

### ISSUE THREAD

**Issue by futureboy37** [jwagenleitner/groovy-wslite#95]
I'm having a bear of a time getting my rest client to set the content length for my request, and the server is throwing back HTTP error code 411 (length required) without it. I've tried everything... even 4 Content-Length headers:

    def response = client.post(path:'/path/to/service', accept: ContentType.JSON) {
	  type ContentType.JSON
	  query:[address: location]
	  headers: ["Content-Length":0,"Content-Length":"0", "ContentLength":"0", "ContentLength":0]
    }	

Nothing works. How can I accomplish this?

**Comment by jwagenleitner** [comment]
If you want to specify your own Content-Length you would do like this:

```groovy
client.post(path:'/path/to/service', 
                     accept: ContentType.JSON, 
                     headers: ['Content-Length':1024]) 
{
....
}
```

The `query` and `headers` params need to go in the method arguments and not in the closure body.

**Comment by futureboy37** [comment]
I tried that, see the example I posted. Perhaps the problem is I set the content-length to 0? But in my case I didn't actually post any data, just set the content type and the query parameters, but no actual form content was sent. Maybe there is some other data being sent? Is there an easy way to get the content length if I'm not intending to actually send data?

**Comment by jwagenleitner** [comment]
In the example you posted you have the `headers` in the closure body, it doesn't belong there.  See my example of where to place it.

**Comment by jwagenleitner** [comment]
The `Content-Length` header should only be set if the request contains data.  If you aren't posting data it shouldn't be added.

https://github.com/jwagenleitner/groovy-wslite/blob/master/src/main/groovy/wslite/http/HTTPClient.groovy#L113
